export default [
  {
    id: 1,
    name: 'Produto exemplo tal ',
    quantity: 50,
    category: 'categoria',
    company: 'sec brasil',
    image: '',
    description: 'taltaltaltalalslsa als sal asasa sas asllsaffabfiasf',
    create_at: '20 dez 2020',
    client: 'Prologis Cajamar'
  },
  {
    id: 2,
    name: 'Produto exemplo tal ',
    quantity: 19,
    category: 'categoria',
    company: 'sec brasil',
    image: '',
    description: 'taltaltaltalalslsa als sal asasa sas asllsaffabfiasf',
    create_at: '20 dez 2020',
    client: 'Prologis Cajamar'
  },
  {
    id: 3,
    name: 'Produto exemplo tal ',
    quantity: 5,
    category: 'categoria',
    company: 'sec brasil',
    image: '',
    description: 'taltaltaltalalslsa als sal asasa sas asllsaffabfiasf',
    create_at: '20 dez 2020',
    client: 'Prologis Cajamar'
  },
  {
    id: 4,
    name: 'Produto exemplo tal ',
    quantity: 33,
    category: 'categoria',
    company: 'sec brasil',
    image: '',
    description: 'taltaltaltalalslsa als sal asasa sas asllsaffabfiasf',
    create_at: '20 dez 2020',
    client: 'Prologis Cajamar'
  },
  {
    id: 5,
    name: 'Produto exemplo tal ',
    quantity: 12,
    category: 'categoria',
    company: 'sec brasil',
    image: '',
    description: 'taltaltaltalalslsa als sal asasa sas asllsaffabfiasf',
    create_at: '20 dez 2020',
    client: 'Prologis Cajamar'
  },
  {
    id: 6,
    name: 'Produto exemplo tal ',
    quantity: 12,
    category: 'categoria',
    company: 'sec brasil',
    image: '',
    description: 'taltaltaltalalslsa als sal asasa sas asllsaffabfiasf',
    create_at: '20 dez 2020',
    client: 'Prologis Cajamar'
  },
  {
    id: 7,
    name: 'Produto exemplo tal ',
    quantity: 12,
    category: 'categoria',
    company: 'sec brasil',
    image: '',
    description: 'taltaltaltalalslsa als sal asasa sas asllsaffabfiasf',
    create_at: '20 dez 2020',
    client: 'Prologis Cajamar'
  },
  {
    id: 7,
    name: 'Produto exemplo tal ',
    quantity: 12,
    category: 'categoria',
    company: 'sec brasil',
    image: '',
    description: 'taltaltaltalalslsa als sal asasa sas asllsaffabfiasf',
    create_at: '20 dez 2020',
    client: 'Prologis Cajamar'
  },
  {
    id: 7,
    name: 'Produto exemplo tal ',
    quantity: 12,
    category: 'categoria',
    company: 'sec brasil',
    image: '',
    description: 'taltaltaltalalslsa als sal asasa sas asllsaffabfiasf',
    create_at: '20 dez 2020',
    client: 'Prologis Cajamar'
  },
  {
    id: 7,
    name: 'Produto exemplo tal ',
    quantity: 12,
    category: 'categoria',
    company: 'sec brasil',
    image: '',
    description: 'taltaltaltalalslsa als sal asasa sas asllsaffabfiasf',
    create_at: '20 dez 2020',
    client: 'Prologis Cajamar'
  },
  {
    id: 7,
    name: 'Produto exemplo tal ',
    quantity: 12,
    category: 'categoria',
    company: 'sec brasil',
    image: '',
    description: 'taltaltaltalalslsa als sal asasa sas asllsaffabfiasf',
    create_at: '20 dez 2020',
    client: 'Prologis Cajamar'
  },
  {
    id: 7,
    name: 'Produto exemplo tal ',
    quantity: 12,
    category: 'categoria',
    company: 'sec brasil',
    image: '',
    description: 'taltaltaltalalslsa als sal asasa sas asllsaffabfiasf',
    create_at: '20 dez 2020',
    client: 'Prologis Cajamar'
  },
  {
    id: 7,
    name: 'Produto exemplo tal ',
    quantity: 12,
    category: 'categoria',
    company: 'sec brasil',
    image: '',
    description: 'taltaltaltalalslsa als sal asasa sas asllsaffabfiasf',
    create_at: '20 dez 2020',
    client: 'Prologis Cajamar'
  },
  {
    id: 7,
    name: 'Produto exemplo tal ',
    quantity: 12,
    category: 'categoria',
    company: 'sec brasil',
    image: '',
    description: 'taltaltaltalalslsa als sal asasa sas asllsaffabfiasf',
    create_at: '20 dez 2020',
    client: 'Prologis Cajamar'
  },
  {
    id: 7,
    name: 'Produto exemplo tal ',
    quantity: 12,
    category: 'categoria',
    company: 'sec brasil',
    image: '',
    description: 'taltaltaltalalslsa als sal asasa sas asllsaffabfiasf',
    create_at: '20 dez 2020',
    client: 'Prologis Cajamar'
  },
  {
    id: 7,
    name: 'Produto exemplo tal ',
    quantity: 12,
    category: 'categoria',
    company: 'sec brasil',
    image: '',
    description: 'taltaltaltalalslsa als sal asasa sas asllsaffabfiasf',
    create_at: '20 dez 2020',
    client: 'Prologis Cajamar'
  },
  {
    id: 7,
    name: 'Produto exemplo tal ',
    quantity: 12,
    category: 'categoria',
    company: 'sec brasil',
    image: '',
    description: 'taltaltaltalalslsa als sal asasa sas asllsaffabfiasf',
    create_at: '20 dez 2020',
    client: 'Prologis Cajamar'
  },
  {
    id: 7,
    name: 'Produto exemplo tal ',
    quantity: 12,
    category: 'categoria',
    company: 'sec brasil',
    image: '',
    description: 'taltaltaltalalslsa als sal asasa sas asllsaffabfiasf',
    create_at: '20 dez 2020',
    client: 'Prologis Cajamar'
  }
]
